version: "3.9"  # optional since v1.27.0
services:
  nginx:
    image: "nginx:latest"
    ports:
      - "${PORT}:80"
    volumes:
      - ./data/log:/var/log
      - ./data/log/nginx:/var/log/nginx
      - ./nginx/${PROTOCOL}/:/etc/nginx/conf.d/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    volumes_from:
      - prometheus
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:  
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    volumes:
      - ./data/prometheus:/prometheus
      - ./prometheus/alerts:/etc/prometheus/alerts
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    links:
      - blackbox
    user: root
  blackbox:
    image: prom/blackbox-exporter:master
    user: "65534"
  heartbeats:
    image: python:latest
    volumes:
      - .:/etc/monitor-client
    environment:
      - UUID=${UUID}
      - SERVER=${SERVER}
    entrypoint: /etc/monitor-client/heartbeats/docker-entrypoint.sh
volumes:
  logvolume01: {}