version: "3.9"  # optional since v1.27.0
services:
  nginx:
    container_name: monitor_worker_nginx
    image: "nginx:alpine"
    ports:
      - "${PORT:-8001}:80"
      - "${PORT_HTTPS:-8444}:443"
    volumes:
      - ./data/log:/var/log
      - ./data/log/nginx:/var/log/nginx
      - ./nginx/conf/${NGINX:-local}/:/etc/nginx/conf.d/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      # Setup logrotate with install, config, and daily script to run 
      - ./nginx/logrotate/entrypoint.sh:/docker-entrypoint.d/31-logrotate.sh
      - ./nginx/logrotate/logrotate.sh:/etc/conf.d/logrotate
      - ./nginx/logrotate/docker-nginx:/etc/logrotate.d/nginx
    volumes_from:
      - prometheus
      - alertmanager
  certbot:
    container_name: monitor_worker_certbot
    image: certbot/certbot
    profiles:
      - prod
    volumes:  
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  prometheus:
    container_name: monitor_worker_prometheus
    image: prom/prometheus:v2.30.3
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      # - '--web.route-prefix=/prometheus'
      # - '--web.listen-address=:8001'
      - '--web.enable-lifecycle'
    volumes:
      - ./data/prometheus:/prometheus
      - ./prometheus/alerts:/etc/prometheus/alerts
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    links:
      - blackbox
    user: root
  alertmanager:
    container_name: monitor_worker_alertmanager
    image: quay.io/prometheus/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager/data'
    volumes:
      - ./data/alertmanager:/alertmanager
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  blackbox:
    container_name: monitor_worker_blackbox
    image: prom/blackbox-exporter:v0.19.0
    command:
      - '--config.file=/etc/prometheus/blackbox.yml'
    user: "65534"
    volumes:
      - ./blackbox/blackbox.yml:/etc/prometheus/blackbox.yml:ro
  heartbeats:
    container_name: monitor_worker_heartbeats
    image: python:latest
    volumes:
      - .:/etc/monitor-worker
    environment:
      - UUID=${UUID}
      - SERVER=${SERVER}
      - PROTOCOL=${SERVER_PROTOCOL}
      - PYTHONUNBUFFERED=1
    entrypoint: /etc/monitor-worker/heartbeats/docker-entrypoint.sh
    ports:
      - "80:80"
volumes:
  logvolume01: {}