global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
- /etc/prometheus/alerts/*.yml
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    basic_auth:
      username: YOUR_USERNAME
      password: YOUR_PASSWORD
    api_version: v1
    static_configs:
    - targets:
      - alertmanager.sebastienbarbier.com
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: alertmanager
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  static_configs:
  - targets:
    - alertmanager.sebastienbarbier.com
- job_name: sebastienbarbier
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - fr-1.sebastienbarbier.com:9100
    - fr-2.sebastienbarbier.com:9100
    - ca-1.sebastienbarbier.com:9100
- job_name: blackbox
  metrics_path: /probe
  scrape_interval: 1h
  params:
    module:
    - http_2xx
  static_configs:
  - labels:
      user: sbarbier
    targets:
    - https://whereis.sebastienbarbier.com
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115
- job_name: blackbox-2
  metrics_path: /probe
  scrape_interval: 1m
  params:
    module:
    - http_2xx
  static_configs:
  - labels:
      user: seven23
    targets:
    - https://seven23.io
    - https://test.seven23.io
    - https://app.seven23.io
    - https://next.seven23.io
  - labels:
      user: sbarbier
    targets:
    - https://sebastienbarbier.com
    - https://blog.sebastienbarbier.com
    - https://sebastienbarbier.fr
    - https://fromedwin.com
    - https://grafana.sebastienbarbier.com
    - https://status.fromedwin.com/healthy/1/
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115
